name:  LightFace
author:  davidwalsh
current:  0.5
category:  Interface
tags:  [lightbox,facebook,overlay,modal,overlay]
docs:  http://davidwalsh.name/js/lightface
demo:  http://davidwalsh.name/dw-content/lightface.php